<?php
/**
 * ScheduledTransactionResponseDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * ScheduledTransactionResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduledTransactionResponseData
 * @package     YNAB
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScheduledTransactionResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduledTransactionResponseData"
     */
    public function testScheduledTransactionResponseData()
    {
    }

    /**
     * Test attribute "scheduledTransaction"
     */
    public function testPropertyScheduledTransaction()
    {
    }
}
