<?php
/**
 * ScheduledTransactionDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * ScheduledTransactionDetailTest Class Doc Comment
 *
 * @category    Class
 * @description ScheduledTransactionDetail
 * @package     YNAB
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScheduledTransactionDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduledTransactionDetail"
     */
    public function testScheduledTransactionDetail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "dateFirst"
     */
    public function testPropertyDateFirst()
    {
    }

    /**
     * Test attribute "dateNext"
     */
    public function testPropertyDateNext()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "flagColor"
     */
    public function testPropertyFlagColor()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "payeeId"
     */
    public function testPropertyPayeeId()
    {
    }

    /**
     * Test attribute "categoryId"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "transferAccountId"
     */
    public function testPropertyTransferAccountId()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "accountName"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "payeeName"
     */
    public function testPropertyPayeeName()
    {
    }

    /**
     * Test attribute "categoryName"
     */
    public function testPropertyCategoryName()
    {
    }

    /**
     * Test attribute "subtransactions"
     */
    public function testPropertySubtransactions()
    {
    }
}
