<?php
/**
 * TransactionSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace YNAB;

use PHPUnit\Framework\TestCase;

/**
 * TransactionSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionSummary
 * @package     YNAB
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionSummary"
     */
    public function testTransactionSummary()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "cleared"
     */
    public function testPropertyCleared()
    {
    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {
    }

    /**
     * Test attribute "flagColor"
     */
    public function testPropertyFlagColor()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "payeeId"
     */
    public function testPropertyPayeeId()
    {
    }

    /**
     * Test attribute "categoryId"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "transferAccountId"
     */
    public function testPropertyTransferAccountId()
    {
    }

    /**
     * Test attribute "transferTransactionId"
     */
    public function testPropertyTransferTransactionId()
    {
    }

    /**
     * Test attribute "matchedTransactionId"
     */
    public function testPropertyMatchedTransactionId()
    {
    }

    /**
     * Test attribute "importId"
     */
    public function testPropertyImportId()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }
}
