<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  YNAB
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace YNAB;

use \YNAB\Configuration;
use \YNAB\ApiException;
use \YNAB\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  YNAB
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTransaction
     *
     * Create a single transaction or multiple transactions.
     *
     */
    public function testCreateTransaction()
    {
    }

    /**
     * Test case for getTransactionById
     *
     * Single transaction.
     *
     */
    public function testGetTransactionById()
    {
    }

    /**
     * Test case for getTransactions
     *
     * List transactions.
     *
     */
    public function testGetTransactions()
    {
    }

    /**
     * Test case for getTransactionsByAccount
     *
     * List account transactions.
     *
     */
    public function testGetTransactionsByAccount()
    {
    }

    /**
     * Test case for getTransactionsByCategory
     *
     * List category transactions.
     *
     */
    public function testGetTransactionsByCategory()
    {
    }

    /**
     * Test case for getTransactionsByPayee
     *
     * List payee transactions.
     *
     */
    public function testGetTransactionsByPayee()
    {
    }

    /**
     * Test case for updateTransaction
     *
     * Updates an existing transaction.
     *
     */
    public function testUpdateTransaction()
    {
    }

    /**
     * Test case for updateTransactions
     *
     * Update multiple transactions.
     *
     */
    public function testUpdateTransactions()
    {
    }
}
